size(2000,1500);
import fontsize;
defaultpen(fontsize(90pt));
pen p = 5+black;
pen f = grey+opacity(0.4);
real A = 60, B = 100, C = 300;
dot((0,0),20+black);
draw(circle((0,0),1),p);
draw((Cos(A),Sin(A))--(Cos(B),Sin(B))--(Cos(C),Sin(C))--cycle,p);
fill((Cos(A),Sin(A))--(Cos(B),Sin(B))--(Cos(C),Sin(C))--cycle,f);